### ISSUE TITLE
Question on zero-volume structures

### ISSUE THREAD

**Issue by jtorresfabra** [hjwdzh/ManifoldPlus#1]
Hey @hjwdzh , 

First of all thanks for sharing your great work. 

I have a question (more than being an issue). Sometimes I need to work with flat surfaces (meaning no enclosed volumes), just planes with some borders. Sometimes these surfaces have non manifold vertices/faces/edges. I'm wondering if there is a way to use ManifoldPlus on this surfaces without the need of building the "other side" of the surface (opposite normal and the need of using double sided lighting for meshlab etc). 

I understand a surface with borders does not really comply the concept of watertight manifold, but I'm looking for a way to "fix" those surfaces using ManifoldPlus. 

What do you think? Am I making sense?
Thanks for your time.

**Comment by hjwdzh** [comment]
Thanks for your question. It is actually a dilemma --
If you have a "T", it is inevitable to get a non-manifold without double face on the other side. Therefore, maybe a different problem should be clearly formulated to solve your question, e.g. what is the ideal way to model a T.

Unfortunately, my current solution cannot handle this problem.

**Comment by jtorresfabra** [comment]
makes sense. Thanks again for your work and your time
