### ISSUE TITLE
Requires Manifold?

### ISSUE THREAD

**Issue by eyildiz-ugoe** [hjwdzh/ManifoldPlus#16]
Does ManifoldPlus require Manifold? I don't have it, and I cannot seem to run any of the examples:

```
~/Desktop/ManifoldPlus/build$ ./manifold -input ../data/table.off --output ../results/table_manifold.obj
##################### Arguments #####################
depth: 8.
input: ../examples/input.obj.
output: ../results/table_manifold.obj.
#####################################################
vertex number: 0    face number: 0
```
```
~/Desktop/ManifoldPlus$ sh examples.sh 
examples.sh: 2: ./build/ManifoldPlus: not found
examples.sh: 3: ./build/ManifoldPlus: not found
examples.sh: 4: ./build/ManifoldPlus: not found
examples.sh: 5: ./build/ManifoldPlus: not found


```

**Comment by Link-K** [comment]
俺也一样
./build/manifold --input data/bunny.obj --output results/bunny.obj --depth 8
##################### Arguments #####################
depth: 8.
input: data/bunny.obj.
output: results/bunny.obj.
#####################################################
vertex number: 35947    face number: 0
段错误 (核心已转储)

**Comment by Link-K** [comment]
> 俺也一样 ./build/manifold --input data/bunny.obj --output results/bunny.obj --depth 8 ##################### Arguments ##################### depth: 8. input: data/bunny.obj. output: results/bunny.obj. ##################################################### vertex number: 35947 face number: 0 段错误 (核心已转储)

解决了，是数据的问题。
