### ISSUE TITLE
./manifold --input input.obj --output output.obj --depth 8

### ISSUE THREAD

**Issue by zyz-notebooks** [hjwdzh/ManifoldPlus#4]
段错误 (核心已转储)
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

**Comment by hjwdzh** [comment]
That's interesting, since I have not seen this issue by testing thousands of models. Would you mind sending me the testing data (input.obj) to jingweih@stanford.edu ?

**Comment by zyz-notebooks** [comment]
> That's interesting, since I have not seen this issue by testing thousands of models. Would you mind sending me the testing data (input.obj) to [jingweih@stanford.edu](mailto:jingweih@stanford.edu) ?

hi, I have solved this problem, but when I use the output watertight mesh for data rendering on [PIFU](https://github.com/shunsukesaito/PIFu/issues/32#issuecomment-641707924), I have encountered a problem, it seems that the reconstruction of the manifold will destroy the uv mapping, please do you have any suggestions, thank you very much

**Comment by hjwdzh** [comment]
This is not included. However, there is a simple solution for this -- try this function: https://github.com/libigl/libigl/blob/master/include/igl/point_mesh_squared_distance.h

You will be able to find the closest point on the original mesh for each point in the manifold -- from which you can compute the barycentric coordinate and do the interpolation to get the uv.

**Comment by zhan-xu** [comment]
@zyz-1998 can I ask how did you solve the problem?

**Comment by ujjawalcse** [comment]
You can use DataTransfer option in blender to transfer uv from source to destination object.
