### ISSUE TITLE
Artifacts in the results

### ISSUE THREAD

**Issue by jdumas** [hjwdzh/ManifoldPlus#5]
Hi,

Thanks for sharing your code. When I run it on the example provided in this repository, it looks quite different from the renderings advertised in the paper.

E.g., the bedpost frame has spikes on it:
![Screen Shot 2020-06-15 at 1 36 41 AM](https://user-images.githubusercontent.com/578702/84636477-7e4e7b00-aea9-11ea-9a6a-e3f5428382f1.png)

On the bathtub model, I am seeing overlapping flipped faces on the joints, where the model is supposed to be solid:
![bathtub](https://user-images.githubusercontent.com/578702/84638964-8bb93480-aeac-11ea-9dbd-d841143ea400.png)
![Screen Shot 2020-06-15 at 1 44 16 AM](https://user-images.githubusercontent.com/578702/84638970-8e1b8e80-aeac-11ea-88cf-28512bdb2320.png)

For the bathtub itself I understand that it's a single sheet of triangles, so there is no inside/outside properly defined. But in the corner/joint there shouldn't be any artifacts no?

And finally when I tried it on the london model from AccuCities, I'm getting some artifacts along sharp features, where things get more "spiky", e.g. on this building on the lower-left of the rendered result: 
![Screen Shot 2020-06-15 at 1 31 22 AM](https://user-images.githubusercontent.com/578702/84639120-ca4eef00-aeac-11ea-894c-0977f06a6627.png)

**Comment by hjwdzh** [comment]
Thanks for posting the issue.

For the bathtub, it is reasonable since the input is a thin structure, which means faces at two sides are stitched together -- in which case back face rendering will have this issue.

For the spikes, the internal reason is complex:
1. there is no guarantee that the optimization always achieve the global optimal.
2. I did not use exact arithmetic so that there could be numerical issues.

I also observe the same problem. However, a higher resolution will definitely alleviate the problem. The rendering I posted is rendered with depth=9.

Finally, I should mention that it is not the perfect solution, and I am keeping developing more fundamental solutions:) Please wait for a more advanced version coming out in months:)

**Comment by jdumas** [comment]
> For the bathtub, it is reasonable since the input is a thin structure, which means faces at two sides are stitched together -- in which case back face rendering will have this issue.

Hmm I guess I'm used to the way TetWild closes the "solid" part of the shape using the generalized winding number. In the case of the bathtub, even though the input mesh is open, you can still view it as a closed volume using generalized winding number. In that case, I would expect the walls/corners of the base on the left to not exhibit overlapping flipped faces.

In general, it's an ill-posed problem to try to mix SDF (for solid volumes) and unsigned DF (for flat sheets). You should be able to pick one option, and avoid overlapping faces in both cases. Mixing the two sounds like a lot of trouble.

> I also observe the same problem. However, a higher resolution will definitely alleviate the problem. The rendering I posted is rendered with depth=9.

With depth=9, the pillars are indeed improved, but there are still some artifacts under the pillow unfortunately.

> Finally, I should mention that it is not the perfect solution, and I am keeping developing more fundamental solutions:) Please wait for a more advanced version coming out in months:)

Cool! Looking forward to this!

**Comment by jiangzhongshi** [comment]
Hi,

This is a probably related issue: as I am trying to clean the following model, but I am only able to get a result with artifacts and self-intersections in the output.
[input.obj.zip](https://github.com/hjwdzh/ManifoldPlus/files/4827403/input.obj.zip)


![Screen Shot 2020-06-24 at 3 01 34 PM](https://user-images.githubusercontent.com/12759319/85616385-9fdaff80-b62b-11ea-86f4-6b046a1edf91.png)

**Comment by hjwdzh** [comment]
Hi Zhongshi, this is currently a limitation, that coarse resolution results in bad approximation. I tried your example with depth=9 and it looks much better.
