### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by zshyang** [hjwdzh/ManifoldPlus#9]
I tried to follow the steps in readme.
![Screenshot from 2020-10-20 22-58-27](https://user-images.githubusercontent.com/57812785/96679060-cf72ed80-1327-11eb-8646-3b1d4e65d505.png)
But I got the follow results.
![Screenshot from 2020-10-20 23-00-55](https://user-images.githubusercontent.com/57812785/96679240-1f51b480-1328-11eb-884e-859eb6d90770.png)

**Comment by unlugi** [comment]
I have a suggestion;
Can you please try replacing  all "./build/ManifoldPlus" with "./build/manifold" and then running example.sh?

**Comment by zshyang** [comment]
It helps. thanks
